version: '3'
services:
  web:
    container_name: dockerVue
    build: ./docker_vue
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./project:/work
    tty: true
    stdin_open: true
    command: /bin/sh